GET http://localhost:1337

### https://youtu.be/Ud5xKCYQTjM?t=267

POST http://localhost:1337
Content-Type: application/json

{
    "profile": "dental",
    "data": [
        {
            "doctor_id": "6"
        },
        {
            "doctor_id": "69"
        },
        {
            "doctor_id": "168"
        }
    ]
}

###

POST http://localhost:1337
Content-Type: application/json

{
    "profile": "organizationMS",
    "data": [
        {
            "id": "1",
            "text": {
                "status": "generated",
                "div": "<div xmlns='http://www.w3.org/1999/xhtml'><h1>測試網頁原始碼 OwO</h1><p>應該放一些關於此機構的資訊或是FHIR定義的text.div之類的值，但是我尚且不清楚規範，剩下的都丟空值來測試吧!</p></div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "1101010012"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "長庚醫療財團法人台北長庚紀念醫院",
            "telecom": {
                "system": "phone",
                "value": "02 2713 5211"
            },
            "address": {
                "text": "台北市松山區敦化北路１９９號"
            }
        },
        {
            "id": "2",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "10109051704"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "臺北市立聯合醫院忠孝院區",
            "telecom": {
                "system": "phone",
                "value": "02 2786 1288"
            },
            "address": {
                "text": "台北市南港區同德路87號"
            }
        },
        {
            "id": "3",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2000/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "1101010021"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "基督復臨安息日會醫療財團法人臺安醫院",
            "telecom": {
                "system": "phone",
                "value": "02 2771 8151"
            },
            "address": {
                "text": "台北市松山區八德路２段４２４、４２６號"
            }
        },
        {
            "id": "4",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2001/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "431270012"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "國立臺灣大學醫學院附設醫院金山分院",
            "telecom": {
                "system": "phone",
                "value": "02 2498 9898"
            },
            "address": {
                "text": "新北市金山區五湖里玉爐路７號"
            }
        },
        {
            "id": "5",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2002/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "931100015"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "北新醫療社團法人北新醫院",
            "telecom": {
                "system": "phone",
                "value": "02 2620 9199"
            },
            "address": {
                "text": "新北市淡水區忠寮里演戲埔腳１之２號"
            }
        },
        {
            "id": "6",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2003/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "1531010279"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "板橋中興醫院",
            "telecom": {
                "system": "phone",
                "value": "02 2959 0707"
            },
            "address": {
                "text": "新北市板橋區忠孝路１５號"
            }
        },
        {
            "id": "7",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2004/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "1531061230"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "益民醫院",
            "telecom": {
                "system": "phone",
                "value": "02 8991 1050"
            },
            "address": {
                "text": "新北市新莊區中港路１２７號１－４樓"
            }
        },
        {
            "id": "8",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2005/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "132010014"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "衛生福利部桃園醫院",
            "telecom": {
                "system": "phone",
                "value": "03 369 9721"
            },
            "address": {
                "text": "桃園市桃園區中山路１４９２號"
            }
        },
        {
            "id": "9",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2006/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "932020025"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "天成醫療社團法人天晟醫院",
            "telecom": {
                "system": "phone",
                "value": "03 462 9292"
            },
            "address": {
                "text": "桃園市中壢區延平路155號"
            }
        },
        {
            "id": "10",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2007/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "HOI",
                            "display": "Healthcare Organization Identifier"
                        }
                    ],
                    "text": "醫事機構代碼(Healthcare Organization Identifier number)"
                },
                "system": "https://ma.mohw.gov.tw/masearch/SearchBAS-101-1.aspx",
                "value": "1132070011"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "prov",
                        "display": "Healthcare Provider"
                    }
                ],
                "text": "醫事機構"
            },
            "name": "長庚醫療財團法人林口長庚紀念醫院",
            "telecom": {
                "system": "phone",
                "value": "03 328 1200"
            },
            "address": {
                "text": "桃園市龜山區公西里復興街5號、5之7號、文化一路15號"
            }
        },
        {
            "id": "11",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2008/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "200000000A000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "總統府",
            "telecom": {
                "system": "phone",
                "value": "02 2311 3731"
            },
            "address": {
                "text": " 臺北市中正區重慶南路1段122號"
            }
        },
        {
            "id": "12",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2009/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "201000000A000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "中央研究院",
            "telecom": {
                "system": "phone",
                "value": "02 2782 2120"
            },
            "address": {
                "text": "台北市南港區研究院路二段128號"
            }
        },
        {
            "id": "13",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2010/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "301000000A000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "內政部",
            "telecom": {
                "system": "phone",
                "value": "(02)8195-8151"
            },
            "address": {
                "text": "臺北市中正區徐州路5號"
            }
        },
        {
            "id": "14",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2011/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "313520500K000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "台灣自來水股份有限公司第五區管理處",
            "telecom": {
                "system": "phone",
                "value": "05 225 2670"
            },
            "address": {
                "text": "嘉義市民權路293號"
            }
        },
        {
            "id": "15",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2012/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "301020900G000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "玉山國家公園管理處",
            "telecom": {
                "system": "phone",
                "value": "(049) 2773121"
            },
            "address": {
                "text": "南投縣水里鄉中山路一段515號"
            }
        },
        {
            "id": "16",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2013/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "301021000G000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "陽明山國家公園管理處",
            "telecom": {
                "system": "phone",
                "value": "02 2861 3601"
            },
            "address": {
                "text": "臺北市陽明山竹子湖路1-20號"
            }
        },
        {
            "id": "17",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2014/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "307190000N000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "中央存款保險股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02 2397 1155"
            },
            "address": {
                "text": "臺北市中正區南海路3號11樓"
            }
        },
        {
            "id": "18",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2015/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "307250000N000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "臺灣金融控股股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "(02)23493456"
            },
            "address": {
                "text": "臺北市中正區重慶南路一段120號"
            }
        },
        {
            "id": "19",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2016/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "313000000G000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "經濟部",
            "telecom": {
                "system": "phone",
                "value": "02-2321-2200"
            },
            "address": {
                "text": "臺北市中正區福州街15號"
            }
        },
        {
            "id": "20",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2017/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GOI",
                            "display": "Government Organization Identifier"
                        }
                    ],
                    "text": "政府機關代碼(Government Organization Identifier number)"
                },
                "system": "https://pts.fnp.gov.tw/APNPA/common/gorga.do?method=showChooseSearch&modeType=25",
                "value": "313310000K000"
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "govt",
                        "display": "Government"
                    }
                ],
                "text": "政府機關"
            },
            "name": "台灣電力股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02-23651234"
            },
            "address": {
                "text": "臺北市羅斯福路三段242號"
            }
        },
        {
            "id": "21",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2018/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "22099131 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "台灣積體電路製造股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "886-3-5682080"
            },
            "address": {
                "text": "新竹科學園區新竹市力行六路8號"
            }
        },
        {
            "id": "22",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2019/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "22403689 "
            },
            "active": false,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "台晟鋼鐵股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "無"
            },
            "address": {
                "text": "臺北市大安區復興南路2段157號6樓之6"
            }
        },
        {
            "id": "23",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2020/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "22833203 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "台有化學有限公司",
            "telecom": {
                "system": "phone",
                "value": "07-3138409"
            },
            "address": {
                "text": "高雄市苓雅區四維四路2號4樓之2"
            }
        },
        {
            "id": "24",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2021/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "97311466 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "精誠資訊股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02 7720 1888"
            },
            "address": {
                "text": "臺北市內湖區瑞光路318號"
            }
        },
        {
            "id": "25",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2022/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "23525730 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "台灣微軟股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "(886) (2) 3725-3888"
            },
            "address": {
                "text": "臺北市信義區忠孝東路5段68號18樓"
            }
        },
        {
            "id": "26",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2023/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "23060248 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "全家便利商店股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02 2821 2852"
            },
            "address": {
                "text": "臺北市中山區中山北路2段61號7樓"
            }
        },
        {
            "id": "27",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2024/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "22555003 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "統一超商股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02 2747 8711"
            },
            "address": {
                "text": "臺北市松山區東興路8號8樓"
            }
        },
        {
            "id": "28",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2025/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "27934855 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "美商科高國際有限公司 GOOGLE INTERNATIONAL LLC",
            "telecom": {
                "system": "phone",
                "value": "02-87296000"
            },
            "address": {
                "text": "臺北市信義區信義路5段7號73樓之1"
            }
        },
        {
            "id": "29",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2026/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "70472679 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "八方雲集國際股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "02 2623 4588"
            },
            "address": {
                "text": "新北市淡水區中正東路2段27號18樓"
            }
        },
        {
            "id": "30",
            "text": {
                "status": "empty",
                "div": "<div xmlns='http://www.w3.org/2027/xhtml'>空值</div>"
            },
            "identifier": {
                "use": "official",
                "type": {
                    "coding": [
                        {
                            "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/v2-0203",
                            "code": "GUI",
                            "display": "Government Uniform Invoice"
                        }
                    ],
                    "text": "公司行號(Government Uniform Invoice number)"
                },
                "system": "https://findbiz.nat.gov.tw",
                "value": "82822428 "
            },
            "active": true,
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                        "code": "bus",
                        "display": "Non-Healthcare Business or Corporation"
                    }
                ],
                "text": "公司行號(統一編號)"
            },
            "name": "康統醫學科技股份有限公司",
            "telecom": {
                "system": "phone",
                "value": "(02) 3322-1842"
            },
            "address": {
                "text": "臺北市中正區北平東路16號8樓"
            }
        },
        {}
    ]
}