POST http://localhost:1337
Content-Type: application/json

{
  "profile": "conditionMS",
  "data": [
    {
      "id": "1",
      "text": {
        "status": "generated",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'><h1>測試網頁原始碼 OwO</h1><p>應該放一些關於此機構的資訊或是FHIR定義的text.div之類的值，但是我尚且不清楚規範，剩下的都丟空值來測試吧!</p></div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "resolved",
          "display": "Resolved"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "109006",
          "display": "Anxiety disorder of childhood OR adolescence"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A00.0",
          "display": "霍亂"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-1"
      },
      "onsetDateTime": "2021-08-11",
      "abatementDateTime": "2022-06-27",
      "asserter": {
        "reference": "Practitioner/pra-1"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "2",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "remission",
          "display": "Remission"
        },
        "text": "The subject is experiencing a re-occurence or repeating of a previously resolved condition, e.g. urinary tract infection, pancreatitis, cholangitis, conjunctivitis."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "provisional",
          "display": "Provisional"
        },
        "text": "This is a tentative diagnosis - still a candidate that is under consideration."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "problem-list-item",
          "display": "Problem List Item"
        },
        "text": "An item on a problem list that can be managed over time and can be expressed by a practitioner (e.g. physician, nurse), patient, or related person."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6751-7\t",
          "display": "Moderate"
        },
        "text": "Moderate"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "122003",
          "display": "Choroidal hemorrhage"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A00.1",
          "display": "血清型01 cholerae霍亂弧菌所致之霍亂"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-2"
      },
      "onsetDateTime": "2021-05-07",
      "abatementDateTime": "2022-07-28",
      "asserter": {
        "reference": "Practitioner/pra-2"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "3",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "remission",
          "display": "Remission"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "127009",
          "display": "Spontaneous abortion with laceration of cervix"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A00.9",
          "display": "\t血清型01 eltor霍亂弧菌所致之霍亂"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-3"
      },
      "onsetDateTime": "2021-01-20",
      "abatementDateTime": "2022-11-14",
      "asserter": {
        "reference": "Practitioner/pra-3"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "4",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "remission",
          "display": "Remission"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "129007",
          "display": "Homoiothermia"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A01",
          "display": "霍亂"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-4"
      },
      "onsetDateTime": "2021-11-28",
      "abatementDateTime": "2022-07-02",
      "asserter": {
        "reference": "Practitioner/pra-4"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "5",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "inactive",
          "display": "Inactive"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "134006",
          "display": "\tDecreased hair growth"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A01.0",
          "display": "傷寒及副傷寒"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-5"
      },
      "onsetDateTime": "2021-10-07",
      "abatementDateTime": "2022-11-25",
      "asserter": {
        "reference": "Practitioner/pra-5"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "6",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "inactive",
          "display": "Inactive"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "140004",
          "display": "Chronic pharyngitis"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A01.00",
          "display": "傷寒"
        },
        "text": "icd10-cm-2021"
      },
      "subject": {
        "reference": "Patient/pat-6"
      },
      "onsetDateTime": "2021-11-06",
      "abatementDateTime": "2022-05-20",
      "asserter": {
        "reference": "Practitioner/pra-6"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "7",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "resolved",
          "display": "Resolved"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "confirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "144008",
          "display": "Normal peripheral vision"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "https://twcore.mohw.gov.tw/fhir/CodeSystem/icd-10-cm-2021-tw",
          "code": "A00",
          "display": "霍亂"
        },
        "text": "icd10-cm-2014"
      },
      "subject": {
        "reference": "Patient/pat-7"
      },
      "onsetDateTime": "2021-07-21",
      "abatementDateTime": "2022-01-11",
      "asserter": {
        "reference": "Practitioner/pra-7"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "8",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "resolved",
          "display": "Resolved"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "unconfirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "147001",
          "display": "Superficial foreign body of scrotum without major open wound but with infection"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "441769002\t",
          "display": "Cardiac defibrillator in situ (finding)"
        },
        "text": "problemGPSCode"
      },
      "subject": {
        "reference": "Patient/pat-8"
      },
      "onsetDateTime": "2021-11-19",
      "abatementDateTime": "2022-09-14",
      "asserter": {
        "reference": "Practitioner/pra-8"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "9",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "resolved",
          "display": "Resolved"
        },
        "text": "The subject is currently experiencing the symptoms of the condition or there is evidence of the condition."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "unconfirmed",
          "display": "Confirmed"
        },
        "text": "There is sufficient diagnostic and/or clinical evidence to treat this as a confirmed condition."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        },
        "text": "A point in time diagnosis (e.g. from a physician or nurse) in context of an encounter."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6752-5",
          "display": "Mild"
        },
        "text": "Mild"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "150003",
          "display": "Abnormal bladder continence"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "http://hl7.org/fhir/uv/ips/CodeSystem/absent-unknown-uv-ips",
          "code": "no-problem-info",
          "display": "No information about current problems"
        },
        "text": "absentOrUnknownProblem"
      },
      "subject": {
        "reference": "Patient/pat-9"
      },
      "onsetDateTime": "2021-05-28",
      "abatementDateTime": "2022-11-01",
      "asserter": {
        "reference": "Practitioner/pra-9"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    },
    {
      "id": "10",
      "text": {
        "status": "empty",
        "div": "<div xmlns='http://www.w3.org/1999/xhtml'>空值</div>"
      },
      "clinicalStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
          "code": "resolved",
          "display": "Resolved"
        },
        "text": "The subject is no longer experiencing the symptoms of the condition and there is a negligible perceived risk of the symptoms returning."
      },
      "verificationStatus": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
          "code": "refuted",
          "display": "Refuted"
        },
        "text": "This condition has been ruled out by diagnostic and clinical evidence."
      },
      "category": {
        "coding": {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "problem-list-item",
          "display": "Problem List Item"
        },
        "text": "\tAn item on a problem list that can be managed over time and can be expressed by a practitioner (e.g. physician, nurse), patient, or related person."
      },
      "severity": {
        "coding": {
          "system": "http://loinc.org",
          "code": "LA6750-9\t",
          "display": "Severe"
        },
        "text": "Severe"
      },
      "code": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "151004",
          "display": "Meningitis due to gonococcus"
        },
        "text": ""
      },
      "bodySite": {
        "coding": {
          "system": "http://snomed.info/sct",
          "code": "404684003\t",
          "display": "Clinical finding (finding)"
        },
        "text": "sct"
      },
      "subject": {
        "reference": "Patient/pat-10"
      },
      "onsetDateTime": "2021-04-03",
      "abatementDateTime": "2022-07-19",
      "asserter": {
        "reference": "Practitioner/pra-10"
      },
      "note": {
        "text": "關於此Condition的附加資訊"
      }
    }
  ]
}